apiVersion: v1
kind: Namespace
metadata:
  name: xavifortes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xavifortes-web
  namespace: xavifortes
  labels:
    app: xavifortes-web
    namespace: xavifortes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xavifortes-web
      namespace: xavifortes
  template:
    metadata:
      labels:
        app: xavifortes-web
        namespace: xavifortes
    spec:
      containers:
      - name: xavifortes-web
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: xavifortes-web
  namespace: xavifortes
  labels:
    app: xavifortes-web
    namespace: xavifortes
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: xavifortes-web
    namespace: xavifortes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xavifortes-web
  namespace: xavifortes
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: xavifortes.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xavifortes-web
            port:
              number: 80